#+TITLE:AEON (Another Emacs Operating eNvironment) Introduction and Initialization
#+AUTHOR:Joshua Suskalo
#+PROPERTY: header-args:emacs-lisp :session *emacs-config-session*

* Rationale
  AEON is a literate config for emacs, built around modularity and ease of use.


* Architecture
  :PROPERTIES:
  :header-args: :noweb no-export :tangle no
  :END:
  AEON follows a modular architecture, such that -- aside from some core configurations --
  anything can be included or excluded as desired.

  #+BEGIN_SRC emacs-lisp :tangle yes
    <<core-emacs-configuration>>
    <<load-bootstrap-packages>>
  #+END_SRC

** Initialization
*** Core Appearance and Usability
    Right when emacs is first started, some basic configuration needs to be set.
    That will help ensure that some of the core experience working with it is pleasant.
    #+BEGIN_SRC emacs-lisp :noweb-ref core-emacs-configuration
      <<disable-unnecessary-default-features>>
      <<enable-utf8-support>>
      <<configure-elisp-interpreter>>

      (setq user-full-name "Joshua Suskalo"
            user-mail-address "joshua@suskalo.org")

      (global-font-lock-mode t)

      (setq initial-scratch-message ";; Hello, world!")
    #+END_SRC
**** Disable Unnecessary Features
     Emacs comes filled with some features which are simply unneccessary for most people's workflows,
     many of which are just plain ugly. All of these features are disabled here. If someone really wants
     to use them, they can enable them again in their own config at a later date.
     #+BEGIN_SRC emacs-lisp :noweb-ref disable-unnecessary-default-features
       (when (functionp 'tool-bar-mode)
         (tool-bar-mode -1))
       (when (functionp 'menu-bar-mode)
         (menu-bar-mode -1))
       (when (functionp 'scroll-bar-mode)
         (scroll-bar-mode -1))
       (when (functionp 'mouse-wheel-mode)
         (mouse-wheel-mode -1))
       (when (functionp 'tooltip-mode)
         (tooltip-mode -1))
       (when (functionp 'blink-cursor-mode)
         (blink-cursor-mode -1))

       (setq ring-bell-function (lambda ())
             inhibit-startup-screen t)
     #+END_SRC
**** Enable UTF-8 Support
     Emacs is a very old text editor, and doesn't come with UTF-8 support pre-enabled.
     UTF-8 is rather important to modern file editing however, so it should be enabled by default.
     #+BEGIN_SRC emacs-lisp :noweb-ref enable-utf8-support
       (set-charset-priority 'unicode)
       (set-default-coding-systems 'utf-8)
       (set-terminal-coding-system 'utf-8)
       (set-keyboard-coding-system 'utf-8)
       (set-selection-coding-system 'utf-8)
       (prefer-coding-system 'utf-8)
       (setq default-process-coding-system '(utf-8-unix . utf-8-unix))
     #+END_SRC
**** Configure the Emacs Lisp Interpreter
     The emacs lisp interpreter has many default settings which are out of date for modern computers.
     The garbage collector doesn't need to be run as often as it currently is. The message
     buffer can have a lot more messages in it, and cl features should be loaded.
     #+BEGIN_SRC emacs-lisp :noweb-ref configure-elisp-interpreter
       (require 'cl-lib)

       (setq message-log-max 16384
             gc-cons-threshold (* 50 1024 1024)
             jit-lock-stealth-time 1
             jit-lock-stealth-verbose nil)
     #+END_SRC
** Load Bootstrap Packages
   AEON's module system is based on a few core things in order to have a well-defined syntax and layout. These packages are needed to properly get that rolling.
   #+BEGIN_SRC emacs-lisp :noweb-ref load-bootstrap-packages
     <<use-package-configuration>>
   #+END_SRC
*** Use-package Installation and Configuration
    straight.el is the package manager used by AEON, but use-package provides a great interface to other package managers.

    First AEON installs use-package, then we configure use-package to always use straight.el by default.
    #+BEGIN_SRC emacs-lisp :noweb-ref use-package-configuration
      (straight-use-package 'use-package)
      (setq straight-use-package-by-default t)
    #+END_SRC
